/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    KpDictTag: typeof import('./components/business/KpDictTag/index.vue')['default']
    KpFont: typeof import('./components/common/KpFont/index.vue')['default']
    KpFooter: typeof import('./components/layout/KpFooter/index.vue')['default']
    KpHeader: typeof import('./components/layout/KpHeader/index.vue')['default']
    KpLang: typeof import('./components/common/KpLang/index.vue')['default']
    KpModal: typeof import('./components/business/KpModal/index.vue')['default']
    KpNotice: typeof import('./components/common/KpNotice/index.vue')['default']
    KpOperation: typeof import('./components/business/KpOperation/index.vue')['default']
    KpPagination: typeof import('./components/business/KpPagination/index.vue')['default']
    KpQuery: typeof import('./components/business/KpQuery/index.vue')['default']
    KpScreen: typeof import('./components/common/KpScreen/index.vue')['default']
    KpSearch: typeof import('./components/common/KpSearch/index.vue')['default']
    KpSelect: typeof import('./components/business/KpSelect/index.vue')['default']
    KpSetting: typeof import('./components/common/KpSetting/index.vue')['default']
    KpSideMenu: typeof import('./components/navigation/KpSideMenu/index.vue')['default']
    KpTable: typeof import('./components/business/KpTable/index.vue')['default']
    KpTabs: typeof import('./components/layout/KpTabs/index.vue')['default']
    KpTheme: typeof import('./components/common/KpTheme/index.vue')['default']
    KpToolbar: typeof import('./components/business/KpToolbar/index.vue')['default']
    KpTopMenu: typeof import('./components/navigation/KpTopMenu/index.vue')['default']
    KpTreeSelect: typeof import('./components/business/KpTreeSelect/index.vue')['default']
    KpUser: typeof import('./components/common/KpUser/index.vue')['default']
    KpVirtualSelect: typeof import('./components/business/KpVirtualSelect/index.vue')['default']
    KpVirtualTable: typeof import('./components/business/KpVirtualTable/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
