/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BasicLayout: typeof import('./layouts/BasicLayout.vue')['default']
    KpBreadcrumb: typeof import('./components/navigation/KpBreadcrumb/index.vue')['default']
    KpDictTag: typeof import('./components/common/KpDictTag/index.vue')['default']
    KpFontSize: typeof import('./components/common/KpFontSize/index.vue')['default']
    KpFooter: typeof import('./components/navigation/KpFooter/index.vue')['default']
    KpFullscreen: typeof import('./components/common/KpFullscreen/index.vue')['default']
    KpHeader: typeof import('./components/navigation/KpHeader/index.vue')['default']
    KpLocale: typeof import('./components/common/KpLocale/index.vue')['default']
    KpNotice: typeof import('./components/common/KpNotice/index.vue')['default']
    KpSearch: typeof import('./components/common/KpSearch/index.vue')['default']
    KpSelect: typeof import('./components/business/KpSelect/index.vue')['default']
    KpSettings: typeof import('./components/common/KpSettings/index.vue')['default']
    KpSider: typeof import('./components/navigation/KpSider/index.vue')['default']
    KpTheme: typeof import('./components/common/KpTheme/index.vue')['default']
    KpTopMenu: typeof import('./components/navigation/KpTopMenu/index.vue')['default']
    KpUser: typeof import('./components/common/KpUser/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
